- name: install mariadb (CentOS/Fedora)
  tags: centos,db,mariadb
  dnf:
    name: mariadb
    state: latest
  when: ansible_distribution in ["CentOS", "Fedora"]

- name: install mariadb package (Ubuntu/Debian)
  tags: ubuntu,db,mariadb
  apt:
    name: mariadb-server
    state: latest
  when: ansible_distribution in ["Ubuntu", "Debian"]
