---

- hosts: all
  become: true
  pre_tasks:

  - name: Install updates (CentOS/Fedora)
    tags: always
    dnf:
      update_only: yes
      update_cache: yes
    when: ansible_distribution in ["CentOS", "Fedora"]

  - name: Install updates (Ubuntu/Debian)
    tags: always
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution in ["Ubuntu", "Debian"]


- hosts: workstations
  become: true
  tasks:
  
  - name: install unzip
    package:
      name: unzip

  - name: install terraform
    unarchive:
      src: https://releases.hashicorp.com/terraform/1.7.5/terraform_1.7.5_linux_amd64.zip
      dest: /usr/local/bin/
      remote_src: yes
      mode: 0755
      owner: root
      group: root

- hosts: web_servers
  become: true
  tasks:

  - name: install apache and php for (CentOS/Fedora)
    tags: apache,centos,httpd
    dnf:
      name:
        - httpd
        - php
      state: latest
    when: ansible_distribution in ["CentOS", "Fedora"]

  - name: copy default html file for site
    tags: apache,apache2,httpd
    copy:
      src: /home/mg/ansible/files/default_site.html
      dest: /var/www/html/idex.html
      owner: root
      group: root
      mode: 0644

  - name: copy css file for defaul site
    tags: apache,apache2,httpd
    copy:
      src: /home/mg/ansible/files/styles.css
      dest: /var/www/html/styles.css
      owner: root
      group: root
      mode: 0644

  - name: install apache and php for (Ubuntu/Fedora)
    tags: apache,apache2,ubuntu
    apt:
      name:
        - apache2
        - libapache2-mod-php
      state: latest
    when: ansible_distribution in ["Ubuntu", "Debian"]

- hosts: db_servers
  become: true
  tasks:

  - name: install mariadb (CentOS/Fedora)
    tags: centos,db,mariadb
    dnf:
      name: mariadb
      state: latest
    when: ansible_distribution in ["CentOS", "Fedora"]

  - name: install mariadb package (Ubuntu/Debian)
    tags: ubuntu,db,mariadb
    apt:
      name: mariadb-server
      state: latest
    when: ansible_distribution in ["Ubuntu", "Debian"]

- hosts: file_servers
  become: true
  tasks:

  - name: install samba package
    tags: samba
    package:
      name: samba
      state: latest
